name: pytorch-GeNSeg-Net
channels:
- pytorch
- defaults
dependencies:
- python=3.9
- pytorch=1.12.1
- tensorflow==2.13.0
- scipy
- pip
- pip:
  - dominate==2.7.0
  - torchvision==0.13.1
  - Pillow==9.4.0
  - numpy==1.23.4
  - visdom==0.2.3
  - wandb==0.14.0
  - imageio==2.23.0
  - einops==0.6.1
  - python-dateutil==2.8.2
  - tqdm==4.64.1
  - opencv-python==4.6.0.66

